### ISSUE TITLE
Stopping concentration after having assumed a Wild Shape form can crash the game with NullReferenceException

### ISSUE THREAD

**Issue by casadan** [EnderWiggin/SolastaUnfinishedBusiness#62]
Steps to reproduce:
Prerequisites(*): a druid character who had previously cast a concentration spell and had also transformed to a Wild Shape form (e.g. a Dire Wolf).

1. During the druid's turn, stop concentrating
2. Verify if the spell has stopped

Expected result: the spell effects vanish and the turn continues normally.

Actual result: the spell persists even though the character is no longer concentrating. A "Game Warning!" error appears shortly after this.

(*) The issue is not always reproducible so other yet to identify prerequisites must exist, however, in the attached saved game the crash always occurs.

Mod version: 1.5.97.101
Mod settings: [Settings.xml](https://github.com/user-attachments/files/23322266/Settings.xml)
Savegame: [Test.zip](https://github.com/user-attachments/files/23322285/Test.zip)
Log file: [Player.log](https://github.com/user-attachments/files/23322259/Player.log)

Video:

https://github.com/user-attachments/assets/fbd2af2c-fe23-453d-bd5c-e85e4ae015e4

**Comment by EnderWiggin** [comment]
Fixed the crash, but there's something wrong with that spell effect. Can you try to reproduce this from scratch, and if it does reproduce attach both a save from before casting a spell and after? Either re-open this issue if it reproduces, or create new one.

**Comment by casadan** [comment]
Hi! the issue is still reproducible in the newly released version (1.5.97.104).

After attempting to stop the spell, it does not vanish. The game warning keeps appearing and the round eventually freezes:

https://github.com/user-attachments/assets/3efff105-df15-4c99-96e6-0c3e1a453a2e

Log file: [Player.log](https://github.com/user-attachments/files/23591126/Player.log)

Unfortunately, I do not have a save from just before casting the spell and the earliest available is this auto-save:  [AutoSave_2.zip](https://github.com/user-attachments/files/23591148/AutoSave_2.zip).

I will try to recreate it again and report back tonight if successful. BTW, the issue does not seem specific to that spell, I have also seen it happen when trying to stop a "Spike Growth".

**Comment by casadan** [comment]
@EnderWiggin, I was able to recreate the issue from scratch and narrowed down the steps, turns out that quicksaving was the missing prerequisite:

1. Have the druid cast a concentration spell (e.g. Entangle)
2. Transform to a Wild Shape form (e.g. a Dire Wolf)
3. Hit F5 to quicksave the game
4. Load the quicksave
5. Stop concentrating
6. Verify if the spell has stopped

Here is a video showing the above steps:

https://github.com/user-attachments/assets/a27f8134-3a18-433f-b1e6-e90b04100a46

Log file: [Player.log](https://github.com/user-attachments/files/23595367/Player.log)
Start savegame: [Start.zip](https://github.com/user-attachments/files/23595368/Start.zip)
Quicksave: [QuickSave_8.zip](https://github.com/user-attachments/files/23595374/QuickSave_8.zip)
Post-crash savegame: [Post crash.zip](https://github.com/user-attachments/files/23595379/Post.crash.zip)

PS. I cannot reopen this issue, the button is disabled on my end showing a "You do not have permissions to reopen this issue" tooltip.

**Comment by EnderWiggin** [comment]
Finally fixed the issue - won't fix already broken spell casts, but will prevent future problems.
